@baseURL = http://localhost:3000

### Lista todos os pets com status "available" para adoção

GET {{baseURL}}/public/pets/available 
Content-Type: application/json

### Cadastra um novo usuário (adopter ou admin)

POST {{baseURL}}/auth/register 
Content-Type: application/json

{
    "name": "adopter10",
    "email": "adopter10@email.br",
    "password": "senha123",
    "phone": "54999123456",
    "role": "adopter"
}

### Realiza login e retorna o token JWT - email: adopter@email.br ou admin@email.br e senha: senha123

POST {{baseURL}}/auth/login 
Content-Type: application/json

{
    "email": "adopter10@email.br",
    "password": "senha123"
}

### Lista todos os usuários

GET {{baseURL}}/protected/users 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGVtYWlsLmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxNDE3NTY2LCJleHAiOjE3NTE0MjExNjZ9.bJLpO3oPwB0qKcpC5ctxkX73GMaA1nluH3Czl9g9d8Q

### Busca usuário por ID

GET {{baseURL}}/protected/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkb3B0ZXIxMEBlbWFpbC5iciIsInJvbGUiOiJhZG9wdGVyIiwiaWF0IjoxNzUxNDE4NjQ3LCJleHAiOjE3NTE0MjIyNDd9.YIdu4aafPa4jC5YnsdOgoKBIj4hsY55qw30CytQrWUc

### Atualiza dados do usuário pelo ID

PUT {{baseURL}}/protected/users/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGVtYWlsLmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxNDE3NTY2LCJleHAiOjE3NTE0MjExNjZ9.bJLpO3oPwB0qKcpC5ctxkX73GMaA1nluH3Czl9g9d8Q
Content-Type: application/json

{
    "phone": "54999123123"
}

### Remove um usuário por ID

DELETE {{baseURL}}/protected/users/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGVtYWlsLmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxNDE3NTY2LCJleHAiOjE3NTE0MjExNjZ9.bJLpO3oPwB0qKcpC5ctxkX73GMaA1nluH3Czl9g9d8Q

### Lista todos os pets (inclusive os adotados)

GET {{baseURL}}/protected/pets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGVtYWlsLmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxNDE3NTY2LCJleHAiOjE3NTE0MjExNjZ9.bJLpO3oPwB0qKcpC5ctxkX73GMaA1nluH3Czl9g9d8Q

### Busca pet por ID

GET {{baseURL}}/protected/pets/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGVtYWlsLmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxNDE3NTY2LCJleHAiOjE3NTE0MjExNjZ9.bJLpO3oPwB0qKcpC5ctxkX73GMaA1nluH3Czl9g9d8Q

### Cadastra um novo pet

POST {{baseURL}}/protected/pets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGVtYWlsLmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxNDE3NTY2LCJleHAiOjE3NTE0MjExNjZ9.bJLpO3oPwB0qKcpC5ctxkX73GMaA1nluH3Czl9g9d8Q
Content-Type: application/json

{
    "name": "JACARE",
    "age": 1,
    "species": "cachorro",
    "size": "small",
    "status": "available",
    "description": "Um cachorro marrom"
}

### Atualiza os dados de um pet

PUT {{baseURL}}/protected/pets/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGVtYWlsLmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxNDE3NTY2LCJleHAiOjE3NTE0MjExNjZ9.bJLpO3oPwB0qKcpC5ctxkX73GMaA1nluH3Czl9g9d8Q
Content-Type: application/json

{
    "name": "xyz"
}

### Remove um pet do sistema (somente se status = available)

DELETE {{baseURL}}/protected/pets/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkb3B0ZXIxMEBlbWFpbC5iciIsInJvbGUiOiJhZG9wdGVyIiwiaWF0IjoxNzUxNDE4NjQ3LCJleHAiOjE3NTE0MjIyNDd9.YIdu4aafPa4jC5YnsdOgoKBIj4hsY55qw30CytQrWUc

### Lista todas as adoções realizadas

GET {{baseURL}}/protected/adoptions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGVtYWlsLmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxNDE3NTY2LCJleHAiOjE3NTE0MjExNjZ9.bJLpO3oPwB0qKcpC5ctxkX73GMaA1nluH3Czl9g9d8Q

### Realiza a adoção de um pet.

POST {{baseURL}}/protected/adoptions 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGVtYWlsLmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxNDE3NTY2LCJleHAiOjE3NTE0MjExNjZ9.bJLpO3oPwB0qKcpC5ctxkX73GMaA1nluH3Czl9g9d8Q
Content-Type: application/json

{
    "user_id": 2,
    "pet_id": 10
}


















### Debug e Legado!
### Rota pública (acesso livre)

GET {{baseURL}}/public/home 
Content-Type: application/json

### Acesso ao painel (rota protegida, requer token de qualquer usuário autenticado)

GET {{baseURL}}/protected/dashboard 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkb3B0ZXJAZW1haWwuYnIiLCJyb2xlIjoiYWRvcHRlciIsImlhdCI6MTc1MDgwMzM2MiwiZXhwIjoxNzUwODA2OTYyfQ.FG_dGWgzvDcYeULjNUIQsslPdBvCQ6R44nHU5SQYzuk

### Acesso à área admin (rota protegida, requer token de usuário com role "admin")

GET {{baseURL}}/protected/admin 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkb3B0ZXJAZW1haWwuYnIiLCJyb2xlIjoiYWRvcHRlciIsImlhdCI6MTc1MDgwMzM2MiwiZXhwIjoxNzUwODA2OTYyfQ.FG_dGWgzvDcYeULjNUIQsslPdBvCQ6R44nHU5SQYzuk

### debug

GET {{baseURL}}/debug/main