@baseURL = http://localhost:3000

### Rota pública (acesso livre)

GET {{baseURL}}/public/home 
Content-Type: application/json

### Lista todos os pets com status "available" para adoção

GET {{baseURL}}/public/pets/available 
Content-Type: application/json

### Cadastra um novo usuário (adopter ou admin)

POST {{baseURL}}/auth/register 
Content-Type: application/json

{
    "name": "admin",
    "email": "admin@email.br",
    "password": "senha123",
    "phone": "54999123456",
    "role": "admin"
}

### Realiza login e retorna o token JWT - email: adopter@email.br ou admin@email.br e senha: senha123

POST {{baseURL}}/auth/login 
Content-Type: application/json

{
    "email": "admin@email.br",
    "password": "senha123"
}

### Lista todos os usuários

GET {{baseURL}}/protected/users 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGVtYWlsLmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxMjk5NTMwLCJleHAiOjE3NTEzMDMxMzB9.Cc7IPn7CRwOeOBG0KD3H1Q4UBBHavkRrw9eEVaxaQPc

### Busca usuário por ID

GET {{baseURL}}/protected/users/4 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGVtYWlsLmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUwODAzMzM2LCJleHAiOjE3NTA4MDY5MzZ9.dG-oDQjS5QivbL6tXDDeASJngNwVrDplmD6-yd3uR00

### Atualiza dados do usuário pelo ID

PUT {{baseURL}}/protected/users/1 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkb3B0ZXJAZW1haWwuYnIiLCJyb2xlIjoiYWRvcHRlciIsImlhdCI6MTc1MDgwODU4MCwiZXhwIjoxNzUwODEyMTgwfQ.UuXZ1cFSNIAMq1NPv9LXaxujZm9RjEnzR4nL8tVUxpM
Content-Type: application/json

{
    "email": "novoTeste@email.br"
}

### Remove um usuário por ID

DELETE {{baseURL}}/protected/users/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGVtYWlsLmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUwODA5Mzc5LCJleHAiOjE3NTA4MTI5Nzl9.5gWgGANM-nlz75KJoOtbJ9Gm-45LVJT99D9xARpATXI

### Lista todos os pets (inclusive os adotados)

GET {{baseURL}}/protected/pets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGVtYWlsLmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxMjk5NTMwLCJleHAiOjE3NTEzMDMxMzB9.Cc7IPn7CRwOeOBG0KD3H1Q4UBBHavkRrw9eEVaxaQPc

### Busca pet por ID

GET {{baseURL}}/protected/pets/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGVtYWlsLmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxMjk5NTMwLCJleHAiOjE3NTEzMDMxMzB9.Cc7IPn7CRwOeOBG0KD3H1Q4UBBHavkRrw9eEVaxaQPc

### Cadastra um novo pet

POST {{baseURL}}/protected/pets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGVtYWlsLmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxMzI5OTY0LCJleHAiOjE3NTEzMzM1NjR9.oANnG-kxj3AxPzgQXxYkmn2obOF7JQmEH9NUe1akZ80
Content-Type: application/json

{
    "name": "Tobi",
    "age": 3,
    "species": "jacaré",
    "size": "large",
    "status": "available",
    "description": "Um jacaré de 3 metros"
}

### Atualiza os dados de um pet

PUT {{baseURL}}/protected/pets/1 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGVtYWlsLmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxMzI5OTY0LCJleHAiOjE3NTEzMzM1NjR9.oANnG-kxj3AxPzgQXxYkmn2obOF7JQmEH9NUe1akZ80
Content-Type: application/json

{
    "name": "Osvaldo"
}

### Remove um pet do sistema (somente se status = available)

DELETE {{baseURL}}/protected/pets/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGVtYWlsLmJyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxMzI5OTY0LCJleHAiOjE3NTEzMzM1NjR9.oANnG-kxj3AxPzgQXxYkmn2obOF7JQmEH9NUe1akZ80

### Acesso ao painel (rota protegida, requer token de qualquer usuário autenticado)

GET {{baseURL}}/protected/dashboard 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkb3B0ZXJAZW1haWwuYnIiLCJyb2xlIjoiYWRvcHRlciIsImlhdCI6MTc1MDgwMzM2MiwiZXhwIjoxNzUwODA2OTYyfQ.FG_dGWgzvDcYeULjNUIQsslPdBvCQ6R44nHU5SQYzuk

### Acesso à área admin (rota protegida, requer token de usuário com role "admin")

GET {{baseURL}}/protected/admin 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkb3B0ZXJAZW1haWwuYnIiLCJyb2xlIjoiYWRvcHRlciIsImlhdCI6MTc1MDgwMzM2MiwiZXhwIjoxNzUwODA2OTYyfQ.FG_dGWgzvDcYeULjNUIQsslPdBvCQ6R44nHU5SQYzuk

### debug

GET {{baseURL}}/debug/main